### ISSUE TITLE
Not working with `.norg` filetype?

### ISSUE THREAD

**Issue by xfzv** [folke/todo-comments.nvim#106]
I've started using [Neorg](https://github.com/nvim-neorg/neorg/) lately. Comments in `.norg` files can be inserted with [`+comment+`](https://github.com/nvim-neorg/neorg/blob/main/docs/NFF-0.1-spec.md?plain=1#L133). I'm not sure if I missed something but `todo-comments.nvim` doesn't seem to work with `.norg` filetype, although it works just fine for other languages:

- `.norg:`
![norg](https://user-images.githubusercontent.com/78810647/166518870-c0c71409-e8ba-4c10-80cb-ad841c4081d9.png)

- `.lua`:
![lua](https://user-images.githubusercontent.com/78810647/166518877-272b3679-0d7e-4b0a-97d5-aeeb071c005c.png)

Any idea?

Thanks!

**Comment by mrossinek** [comment]
I just ran into the same issue. It appears that this is due to the fact that this plugin checks for the specific node name `comment`, which we so far do not use in Neorg. I just pushed a fix for that to Neorg `main` so you should be able to use this as expected now :+1:

**Comment by xfzv** [comment]
> I just ran into the same issue. It appears that this is due to the fact that this plugin checks for the specific node name `comment`, which we so far do not use in Neorg. I just pushed a fix for that to Neorg `main` so you should be able to use this as expected now +1

Thank you! Can confirm that it now works as expected:

![image](https://user-images.githubusercontent.com/78810647/168486413-d3982564-dc27-42ac-9061-0826650dc6b9.png)

`@TODO` and `@hack` aren't highlighted though (works with other file types) but it's not a big deal. Maybe you can find a workaround too on Neorg side so I'll just close this.

**Comment by MyraBaba** [comment]
@xfzv 

I updated the neorg but still not seen the colours as above 

<img width="163" alt="Screen Shot 2022-05-20 at 16 30 42" src="https://user-images.githubusercontent.com/17505439/169538564-30b29d7b-ec1f-4f80-bdc9-67901f53ff28.png">

**Comment by max397574** [comment]
did u also update the parser?

**Comment by max397574** [comment]
update the parser

**Comment by MyraBaba** [comment]
@xfzv parser you mean todo-comment ?

**Comment by MyraBaba** [comment]
@xfzv if you mean .

:Neorg sync-parsers

its not available in my config.

**Comment by max397574** [comment]
:TSUpdate norg

**Comment by MyraBaba** [comment]
@xfzv 

It says parsers update but still not working.

here my config: 

```

> 
--[[
lvim is the global options object

Linters should be
filled in as strings with either
a global executable or a path to
an executable
]]
-- THESE ARE EXAMPLE CONFIGS FEEL FREE TO CHANGE TO WHATEVER YOU WANT

-- general
vim.opt.smartindent = true
vim.opt.cursorcolumn = true
lvim.log.level = "warn"
lvim.format_on_save = true
lvim.colorscheme = "tokyonight"
-- to disable icons and use a minimalist setup, uncomment the following
-- lvim.use_icons = false

-- keymappings [view all the defaults by pressing <leader>Lk]
lvim.leader = "space"

-- add your own keymapping
lvim.keys.normal_mode["<C-s>"] = ":w<cr>"
-- unmap a default keymapping
-- lvim.keys.normal_mode["<C-Up>"] = false
-- edit a default keymapping
-- lvim.keys.normal_mode["<C-q>"] = ":q<cr>"

-- Change Telescope navigation to use j and k for navigation and n and p for history in both input and normal mode.
-- we use protected-mode (pcall) just in case the plugin wasn't loaded yet.
-- local _, actions = pcall(require, "telescope.actions")
-- lvim.builtin.telescope.defaults.mappings = {
--   -- for input mode
--   i = {
--     ["<C-j>"] = actions.move_selection_next,
--     ["<C-k>"] = actions.move_selection_previous,
--     ["<C-n>"] = actions.cycle_history_next,
--     ["<C-p>"] = actions.cycle_history_prev,
--   },
--   -- for normal mode
--   n = {
--     ["<C-j>"] = actions.move_selection_next,
--     ["<C-k>"] = actions.move_selection_previous,
--   },
-- }

-- Use which-key to add extra bindings with the leader-key prefix
-- lvim.builtin.which_key.mappings["P"] = { "<cmd>Telescope projects<CR>", "Projects" }
-- lvim.builtin.which_key.mappings["t"] = {
--   name = "+Trouble",
--   r = { "<cmd>Trouble lsp_references<cr>", "References" },
--   f = { "<cmd>Trouble lsp_definitions<cr>", "Definitions" },
--   d = { "<cmd>Trouble document_diagnostics<cr>", "Diagnostics" },
--   q = { "<cmd>Trouble quickfix<cr>", "QuickFix" },
--   l = { "<cmd>Trouble loclist<cr>", "LocationList" },
--   w = { "<cmd>Trouble workspace_diagnostics<cr>", "Wordspace Diagnostics" },
-- }

-- TODO: User Config for predefined plugins
-- After changing plugin config exit and reopen LunarVim, Run :PackerInstall :PackerCompile
lvim.builtin.alpha.active = true
lvim.builtin.alpha.mode = "dashboard"
lvim.builtin.notify.active = true
lvim.builtin.terminal.active = true
lvim.builtin.nvimtree.setup.view.side = "left"
lvim.builtin.nvimtree.show_icons.git = 0
lvim.builtin.dap.active = true
-- if you don't want all the parsers change this to a table of the ones you want
lvim.builtin.treesitter.ensure_installed = {
  "bash",
  "c",
  "javascript",
  "json",
  "lua",
  "python",
  "typescript",
  "tsx",
  "css",
  "rust",
  "java",
  "yaml",
}

lvim.builtin.treesitter.ignore_install = { "haskell" }
lvim.builtin.treesitter.highlight.enabled = true

local parser_configs = require('nvim-treesitter.parsers').get_parser_configs()

parser_configs.norg = {
  install_info = {
    url = "https://github.com/nvim-neorg/tree-sitter-norg",
    files = { "src/parser.c", "src/scanner.cc" },
    branch = "main"
  },
}

require('nvim-treesitter.configs').setup {
  ensure_installed = { "norg", "cpp", "c", "python" },
  highlight = { -- Be sure to enable highlights if you haven't!
    enable = true,
  }
}
-- generic LSP settings

-- ---@usage disable automatic installation of servers
lvim.lsp.automatic_servers_installation = true

-- ---configure a server manually. !!Requires `:LvimCacheReset` to take effect!!
-- ---see the full default list `:lua print(vim.inspect(lvim.lsp.automatic_configuration.skipped_servers))`
-- vim.list_extend(lvim.lsp.automatic_configuration.skipped_servers, { "pyright" })
-- local opts = {} -- check the lspconfig documentation for a list of all possible options
-- require("lvim.lsp.manager").setup("pyright", opts)

-- ---remove a server from the skipped list, e.g. eslint, or emmet_ls. !!Requires `:LvimCacheReset` to take effect!!
-- ---`:LvimInfo` lists which server(s) are skiipped for the current filetype
-- vim.tbl_map(function(server)
--   return server ~= "emmet_ls"
-- end, lvim.lsp.automatic_configuration.skipped_servers)

-- -- you can set a custom on_attach function that will be used for all the language servers
-- -- See <https://github.com/neovim/nvim-lspconfig#keybindings-and-completion>
-- lvim.lsp.on_attach_callback = function(client, bufnr)
--   local function buf_set_option(...)
--     vim.api.nvim_buf_set_option(bufnr, ...)
--   end
--   --Enable completion triggered by <c-x><c-o>
--   buf_set_option("omnifunc", "v:lua.vim.lsp.omnifunc")
-- end

-- -- set a formatter, this will override the language server formatting capabilities (if it exists)
vim.list_extend(lvim.lsp.automatic_configuration.skipped_servers, { "clangd" })

local clangd_bin = "/Users/tulpar/.local/share/nvim/lsp_servers/clangd/clangd/bin/clangd"
-- some settings can only passed as commandline flags `clangd --help`
local clangd_flags = {
  "--all-scopes-completion",
  "--suggest-missing-includes",
  "--background-index",
  "--pch-storage=disk",
  "--cross-file-rename",
  "--log=verbose",
  "--completion-style=detailed",
  "--enable-config", -- clangd 11+ supports reading from .clangd configuration file
  "--clang-tidy",
  --"--clang-tidy-checks=-*,llvm-*,clang-analyzer-*,modernize-*,-modernize-use-trailing-return-type",
  --"--compile-commands-dir=/Users/tulpar/Projects/BClite-AI/",
  -- "--fallback-style=Google",
  -- "--header-insertion=never",
  -- "--query-driver=<list-of-white-listed-complers>"
}



local custom_on_attach = function(client, bufnr)
  require("lvim.lsp").common_on_attach(client, bufnr)
  local opts = { noremap = true, silent = true }
  vim.api.nvim_buf_set_keymap(bufnr, "n", "<leader>lh", "<Cmd>ClangdSwitchSourceHeader<CR>", opts)
end

local opts = {
  cmd = { clangd_bin, unpack(clangd_flags) },
  on_attach = custom_on_attach,
}

require("lvim.lsp.manager").setup("clangd", opts)


local formatters = require "lvim.lsp.null-ls.formatters"
formatters.setup {
  { command = "black", filetypes = { "python" } },
  { command = "isort", filetypes = { "python" } },
  {
    -- each formatter accepts a list of options identical to https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md#Configuration
    command = "prettier",
    ---@usage arguments to pass to the formatter
    -- these cannot contain whitespaces, options such as `--line-width 80` become either `{'--line-width', '80'}` or `{'--line-width=80'}`
    extra_args = { "--print-with", "100" },
    ---@usage specify which filetypes to enable. By default a providers will attach to all the filetypes it supports.
    filetypes = { "typescript", "typescriptreact" },
  },
}

-- -- set additional linters
local linters = require "lvim.lsp.null-ls.linters"
linters.setup {
  { command = "flake8", filetypes = { "python" } },
  {
    -- each linter accepts a list of options identical to https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md#Configuration
    command = "shellcheck",
    ---@usage arguments to pass to the formatter
    -- these cannot contain whitespaces, options such as `--line-width 80` become either `{'--line-width', '80'}` or `{'--line-width=80'}`
    extra_args = { "--severity", "warning" },
  },
  {
    command = "codespell",
    ---@usage specify which filetypes to enable. By default a providers will attach to all the filetypes it supports.
    filetypes = { "javascript", "python" },
  },
}
--FIXME
-- FIX:
-- HACK:
-- @TODO:

--HACK:
--PERF:
-- Additional Plugins
lvim.plugins = {
  { "folke/tokyonight.nvim" },
  { "lunarvim/colorschemes" },
  { "arcticicestudio/nord-vim" },
  { "mg979/vim-visual-multi",
    branch = 'master' },
  {
    "folke/trouble.nvim",
    cmd = "TroubleToggle",
  },
  {
    "folke/todo-comments.nvim",
    event = "BufRead",
    signs = true, -- show icons in the signs column
    sign_priority = 8, -- sign priority
    config = function()
      require("todo-comments").setup()
    end,
  },

  {
    "nvim-neorg/neorg",
    tag = "*",
    config = function()
      require('neorg').setup {
        load = {
          ["core.defaults"] = {},
          ["core.norg.concealer"] = {}, -- Allows for use of icons
          ["core.gtd.ui"] = {
            config = { -- Note that this table is optional and doesn't need to be provided
              -- Configuration here
            }
          },
          ["core.keybinds"] = { -- Configure core.keybinds
            config = {
              default_keybinds = true, -- Generate the default keybinds
              neorg_leader = "<Leader>o"
            }
          },

          ["core.gtd.helpers"] = {},
          ["core.gtd.queries"] = {},
          ["core.norg.qol.toc"] = {
            config = { -- Note that this table is optional and doesn't need to be provided
              -- Configuration here
            }
          },
          ["core.norg.completion"] = {
            config = { -- Note that this table is optional and doesn't need to be provided
              engine = "nvim-cmp"

            }
          },
          ["core.highlights"] = {
            config = {}
          },
          ["core.norg.dirman"] = {
            config = {
              workspaces = {
                work = "~/neorg/work",
                home = "~/neorg/home",
                gtd  = "~/neorg/gtd"
              },
              index = "index.norg",
              autochdir = true,

            }
          },
          ["core.gtd.base"] = {
            config = {
              workspace = "gtd",
            },
          },
        }

      }
    end,
    requires = "nvim-lua/plenary.nvim"

  },
  {
    "itchyny/vim-cursorword",
    event = { "BufEnter", "BufNewFile" },
    config = function()
      vim.api.nvim_command("augroup user_plugin_cursorword")
      vim.api.nvim_command("autocmd!")
      vim.api.nvim_command("autocmd FileType NvimTree,lspsagafinder,dashboard,vista let b:cursorword = 0")
      vim.api.nvim_command("autocmd WinEnter * if &diff || &pvw | let b:cursorword = 0 | endif")
      vim.api.nvim_command("autocmd InsertEnter * let b:cursorword = 0")
      vim.api.nvim_command("autocmd InsertLeave * let b:cursorword = 1")
      vim.api.nvim_command("augroup END")
    end
  },
}


```

**Comment by mrossinek** [comment]
> I updated the neorg but still not seen the colours as above
> 
> <img alt="Screen Shot 2022-05-20 at 16 30 42" width="163" src="https://user-images.githubusercontent.com/17505439/169538564-30b29d7b-ec1f-4f80-bdc9-67901f53ff28.png">

@MyraBaba

Most of those lines are not valid norg syntax. This will likely confuse the parser significantly. So I suggest you try the following contents:
```norg
+PERF:+
+HACK:+
+TODO:+
+NOTE:+
+FIX:+
+WARN:+
```
This should result in something like the following:
![screenshot_1653221524](https://user-images.githubusercontent.com/21973473/169694553-610a7e0b-94b9-4e19-9577-bf30e5fb9b54.png)

Notes/questions:
- do the highlights work correctly in other file types for you? If not, then your todo-comments.nvim installation/configuration is not working.
- is your neorg and norg TS parser installation up-to-date?
- make sure you include the `:` at the end of those keywords because without the colon, todo-comments.nvim does not consider these tags

**Comment by max397574** [comment]
works for me as well

**Comment by MyraBaba** [comment]
After delete and remove norg its now working.

Updating the norg not really pulling the updates.

**Comment by MyraBaba** [comment]
@mrossinek 
There is interesting behaviour 👍 
in the index.norg all is good and working but other linked norg file not showing the highligts

Best

**Comment by MyraBaba** [comment]
Here a different error : MAc os X Catalina

install and reinstall many times but not changed. After install it shows highlights and than gives error and stop working. 
<img width="1292" alt="Screen Shot 2022-05-22 at 18 21 43" src="https://user-images.githubusercontent.com/17505439/169702645-e43c5ce7-3103-4476-96f9-97f89ed89d9f.png">

**Comment by max397574** [comment]
it seems like the first issue again
(that the thing isn't called `comment`)
@vhyrro @mrossinek ?
![Screenshot 2022-10-12 at 21 53 12](https://user-images.githubusercontent.com/81827001/195435202-89c8d458-f586-4faa-81d4-dab41cdf5ad3.png)

**Comment by max397574** [comment]
if works for me
![Screenshot 2022-10-21 at 10 28 25](https://user-images.githubusercontent.com/81827001/197150173-5246d1c2-2ab7-4615-9c4b-471e82af2534.png)

**Comment by max397574** [comment]
@xfzv I think this can be closed now?
