### ISSUE TITLE
Highlight gone after formatting done by null-ls

### ISSUE THREAD

**Issue by gegoune** [folke/todo-comments.nvim#46]
I am evaluating replacing efm with jose-elias-alvarez/null-ls.nvim and have just discovered that with such autocmd `autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_seq_sync()` (tested stylua and eslint formatters configured in null-ls) highlights from TODO comments get cleared. That wasn't the case with efm.

**Comment by folke** [comment]
I actually noticed the same recently. Also diagnostics disappear.

Either way you should post an issue with null-ls. Probably not related to Todo comments?

**Comment by folke** [comment]
Are you sure it's an null ls issue and not a Neovim issue? Does it still work as expected with efm? If not I can look into the issue on the Neovim side

**Comment by gegoune** [comment]
Just tested with efm, highlights remain after saving with automatic formatting. And I am absolutely not sure if it null-ls or nvim. How to check?

**Comment by folke** [comment]
if highlights remain with efm, then I suspect it to be a null-ls issue. The should use the same method as is being used in LSP text edits to apply the text edits in order to preserve virtual text etc

**Comment by Gelio** [comment]
Thanks @folke for fixing this problem end-to-end :smile: I see that https://github.com/jose-elias-alvarez/null-ls.nvim/issues/26 is fixed thanks to https://github.com/jose-elias-alvarez/null-ls.nvim/issues/26#issuecomment-875595386 and I believe this issue can be closed now too. I have tested with neovim nightly and the problem is gone :+1:

**Comment by gegoune** [comment]
Unfortunately still an issue for me on `v0.6.0-dev+03d15d9e0`.

**Comment by Gelio** [comment]
Did you try `v0.6.0-dev+21-gf2205b83c`? That one works for me

**Comment by gegoune** [comment]
No, I haven't, installed head via homebrew just before last message. Didn't see commit from your version in very recent git history of master branch, when is it from?

**Comment by Gelio** [comment]
Hmm... From https://github.com/neovim/neovim/releases/tag/nightly it looks like it was f2205b83c553367a76b6cad04a673077ae150fc1. I'm installing neovim as an appimage, so I can't help you with homebrew :slightly_frowning_face:

**Comment by gegoune** [comment]
Meaning that this is what I have + couple of other things from Folke. Gonna see what he's got to say.

@Gelio Did you try to format buffer with todo comment in line (at the end of the line)?

**Comment by Gelio** [comment]
Yup, here's proof, formatting with prettierd via null-ls, both comments are preserved:

https://user-images.githubusercontent.com/889383/124964023-ce522f80-e020-11eb-9425-333e9791d5b2.mp4

**Comment by gegoune** [comment]
Ah, you need to make a change to the line itself. Since recent merges on null-ls side only changed lines are formatted. To test it, assuming prettier fixes it, indent commented line. Stylua deindents comment and highlighting is gone.

**Comment by Gelio** [comment]
> Ah, you need to make a change to the line itself. Since recent merges on null-ls side only changed lines are formatted

Makes sense, now I can still see the problem:


https://user-images.githubusercontent.com/889383/124966626-d19aea80-e023-11eb-9792-1414c7949537.mp4

**Comment by folke** [comment]
I just pushed a `hacky` fix for this.

The problem seems to come from TreeSitter, who also listens to buffer updates with `nvim_buf_attach` **on_lines**, but seems to clear existing highlights on those lines.

In some cases the handler of `todo-comments` runs first and and such the newly added todo highlights will get cleared by TS.

Added a work-around to delay our highlighting to 5ms

**Comment by gegoune** [comment]
Have just updated and tested, formatting still removes highlights. Maybe my machine is slower and 5ms is not long enough?

Does that expose bigger problem, with how treesitter and other plugins can all override themselves?

**Comment by folke** [comment]
@gegoune I'm further looking into this. Something else might actually be causing this inside todo-comments

**Comment by folke** [comment]
I found the root cause.

We only highlight todos in treesitter comments.

The problem is that the `on_lines` fires, but treesitter hasn't updated it's parser yet. Or at least it doesn't return that range as an actual comment any longer.

I'll work on a proper fix for this case

**Comment by gegoune** [comment]
Fixed in https://github.com/folke/todo-comments.nvim/commit/9b276ebeeced9e15707c27e0b2588e7b3e19d9c5.

**Comment by zalegrala** [comment]
Is there anything for users to do here?  I'm just testing out this plugin and I believe I'm running into this, but on recent versions of both null-ls and todo-comments.
